name: Build Orcus

on:
  push:
    branches: [ net48 ]
  pull_request:
    branches: [ net48 ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout ✨
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH 🔗
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    # Install dependencies
    - name: Install dependencies 📦
      run: nuget restore Orcus.sln

    # Build solution
    - name: Build Orcus for release 🧱
      run: msbuild -nologo -v:m -p:Configuration=Release Orcus.sln

    # Build Artifact
    - name: Archive Orcus.Administration 🧱
      uses: thedoctor0/zip-release@master
      with:
        path: ${{ github.workspace }}\Orcus.Administration\bin\Release\.
        exclusions: '*.xml* *.cmd* *.pdb* *.config* /libraries/*.xml /libraries/*.pdb /libraries/*.config'
        type: 'zip'
        filename: 'Orcus.Administration.zip'

    - name: Archive Orcus.Server 🧱
      uses: thedoctor0/zip-release@master
      with:
        path: ${{ github.workspace }}\Orcus.Server\bin\Release\.
        exclusions: '*.xml* *.cmd* *.pdb* *.config*'
        type: 'zip'
        filename: 'Orcus.Server.zip'

    - name: Archive Orcus.Server.CommandLine 🧱
      uses: thedoctor0/zip-release@master
      with:
        path: ${{ github.workspace }}\Orcus.Server.CommandLine\bin\Release\.
        exclusions: '*.xml* *.cmd* *.pdb* *.config*'
        type: 'zip'
        filename: 'Orcus.Server.CommandLine.zip'
    
    # Create Release
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::Build_$(date +"%Y.%m.%d_%H-%M")"
        
    # Upload Release Asset
    - name: Upload Release Asset 📦
      id: upload-release-asset 
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          Orcus.Administration.zip
          Orcus.Server.zip
          Orcus.Server.CommandLine.zip

